/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interface;
import Business.VitalSign;
import Business.VitalSignHistory;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;


/**
 *
 * @author Abel Philip
 */
public class AbnormalSignsJPanel extends javax.swing.JPanel {
    
    VitalSignHistory vsh;
    ArrayList<VitalSign> list;

    double deafultMax;
    double deafultMin;
    
    
    /**
     * Creates new form AbnormalSignsJPanel
     */
    
    
    public AbnormalSignsJPanel(VitalSignHistory vsh, double deafultMax, double deafultMin) {
        initComponents();
        this.vsh = vsh;
       this.deafultMax = deafultMax;
       this.deafultMin = deafultMin;
       setDefaultTable(deafultMax, deafultMin);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        vitalSignstbl = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        btnViewDetails = new javax.swing.JButton();
        lblTemperature = new javax.swing.JLabel();
        txtTemperatureView = new javax.swing.JTextField();
        lblBloodPressure = new javax.swing.JLabel();
        txtBloodPressureView = new javax.swing.JTextField();
        lblPulse = new javax.swing.JLabel();
        txtPulseView = new javax.swing.JTextField();
        txtDateView = new javax.swing.JTextField();
        lblDate = new javax.swing.JLabel();

        vitalSignstbl.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Date", "Blood Pressure"
            }
        ));
        jScrollPane1.setViewportView(vitalSignstbl);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel1.setText("ABNORMAL");

        btnViewDetails.setText("View Vital Signs");
        btnViewDetails.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViewDetailsActionPerformed(evt);
            }
        });

        lblTemperature.setText("Temperature");

        txtTemperatureView.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTemperatureViewActionPerformed(evt);
            }
        });

        lblBloodPressure.setText("Blood Pressure");

        lblPulse.setText("Pulse");

        txtDateView.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDateViewActionPerformed(evt);
            }
        });

        lblDate.setText("Date");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 767, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(139, 139, 139)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addGap(151, 151, 151)
                            .addComponent(jLabel1))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnViewDetails)
                                .addGap(217, 217, 217))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(lblTemperature)
                                .addComponent(lblBloodPressure)
                                .addComponent(lblPulse)
                                .addComponent(lblDate))
                            .addGap(106, 106, 106)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(txtDateView, javax.swing.GroupLayout.PREFERRED_SIZE, 278, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(txtPulseView, javax.swing.GroupLayout.PREFERRED_SIZE, 278, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(txtBloodPressureView, javax.swing.GroupLayout.PREFERRED_SIZE, 278, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(txtTemperatureView, javax.swing.GroupLayout.PREFERRED_SIZE, 278, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addContainerGap(139, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 607, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jLabel1)
                    .addGap(30, 30, 30)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(52, 52, 52)
                    .addComponent(btnViewDetails)
                    .addGap(53, 53, 53)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lblTemperature)
                        .addComponent(txtTemperatureView, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(44, 44, 44)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lblBloodPressure)
                        .addComponent(txtBloodPressureView, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(44, 44, 44)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lblPulse)
                        .addComponent(txtPulseView, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(44, 44, 44)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lblDate)
                        .addComponent(txtDateView, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnViewDetailsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewDetailsActionPerformed
        // TODO add your handling code here:
                   int selectedRow = vitalSignstbl.getSelectedRow();
                   
                   if(selectedRow>=0){
                       VitalSign vs = (VitalSign) vitalSignstbl.getValueAt(selectedRow, 0);
                       txtTemperatureView.setText(vs.getTemperature()+ "");
                       txtTemperatureView.setEnabled(false);
                       
                       txtBloodPressureView.setText(vs.getBloodPressure()+ "");
                       txtBloodPressureView.setEnabled(false);
                       txtDateView.setText(vs.getDate()+ "");
                       txtDateView.setEnabled(false);
                       txtPulseView.setText(vs.getPulse()+ "");
                       txtPulseView.setEnabled(false);
                   }
                   else {
                       JOptionPane.showMessageDialog(null,"Pease select a row");
                   } 
    }//GEN-LAST:event_btnViewDetailsActionPerformed

    private void txtTemperatureViewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTemperatureViewActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTemperatureViewActionPerformed

    private void txtDateViewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDateViewActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDateViewActionPerformed

    private void populateTable(ArrayList<VitalSign> list) {
       DefaultTableModel dtm = (DefaultTableModel) vitalSignstbl.getModel();
       dtm.setRowCount(0);
       for (VitalSign vs : list) {
           Object row[] = new Object[2];
           row[0] = vs;
           row[1] = vs.getBloodPressure();
           dtm.addRow(row);
       }
   }
    
    private void setDefaultTable(double max, double min) {
       list = vsh.getAbnormalList(max, min);
       initialTextFields();
       populateTable(list);
   }
   private void initialTextFields(){
       txtTemperatureView.setText("");
       txtBloodPressureView.setText("");
       txtPulseView.setText("");
       txtDateView.setText("");
   }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnViewDetails;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblBloodPressure;
    private javax.swing.JLabel lblDate;
    private javax.swing.JLabel lblPulse;
    private javax.swing.JLabel lblTemperature;
    private javax.swing.JTextField txtBloodPressureView;
    private javax.swing.JTextField txtDateView;
    private javax.swing.JTextField txtPulseView;
    private javax.swing.JTextField txtTemperatureView;
    private javax.swing.JTable vitalSignstbl;
    // End of variables declaration//GEN-END:variables
}
