/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interface;
import Business.VitalSignHistory;
import Business.VitalSign;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Abel Philip
 */
public class ViewVitalsJPanel extends javax.swing.JPanel {

    
    /**
     * Creates new form viewVitalsJPanel
     */
    
    private VitalSignHistory vsh;
    public ViewVitalsJPanel(VitalSignHistory vsh) {
          initComponents();
          this.vsh= vsh;
           populateTable();
           
    }
    
    public void populateTable(){
    
    DefaultTableModel dtm= (DefaultTableModel)tblVitalSigns.getModel();
    dtm.setRowCount(0);
    
    for(VitalSign vs : vsh.getVitalSignHistory()){
    
    Object row[]= new Object[2];
    row[0]= vs;
    row[1]= vs.getBloodPressure();
    dtm.addRow(row);
    
    
    }
    
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblVitalSigns = new javax.swing.JTable();
        btnViewDetails = new javax.swing.JButton();
        btnDelete = new javax.swing.JButton();
        lblPulse = new javax.swing.JLabel();
        txtTemperatureView = new javax.swing.JTextField();
        lblDate = new javax.swing.JLabel();
        txtBloodPressureView = new javax.swing.JTextField();
        txtPulseView = new javax.swing.JTextField();
        txtDateView = new javax.swing.JTextField();
        lblTemperature = new javax.swing.JLabel();
        lblBloodPressure = new javax.swing.JLabel();
        btnUpdate = new javax.swing.JButton();

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel1.setText("View Vital Signs");

        tblVitalSigns.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Date", "Blood Pressure"
            }
        ));
        jScrollPane1.setViewportView(tblVitalSigns);

        btnViewDetails.setText("View Vital Signs");
        btnViewDetails.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViewDetailsActionPerformed(evt);
            }
        });

        btnDelete.setText("Delete");
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });

        lblPulse.setText("Pulse");

        txtTemperatureView.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTemperatureViewActionPerformed(evt);
            }
        });

        lblDate.setText("Date");

        txtDateView.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDateViewActionPerformed(evt);
            }
        });

        lblTemperature.setText("Temperature");

        lblBloodPressure.setText("Blood Pressure");

        btnUpdate.setText("Update");
        btnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(227, 227, 227)
                        .addComponent(jLabel1))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(layout.createSequentialGroup()
                            .addContainerGap()
                            .addComponent(btnViewDetails)
                            .addGap(31, 31, 31)
                            .addComponent(btnUpdate)
                            .addGap(26, 26, 26)
                            .addComponent(btnDelete))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                            .addGap(76, 76, 76)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(76, 76, 76)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblTemperature)
                            .addComponent(lblBloodPressure)
                            .addComponent(lblPulse)
                            .addComponent(lblDate))
                        .addGap(106, 106, 106)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtDateView, javax.swing.GroupLayout.PREFERRED_SIZE, 278, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtPulseView, javax.swing.GroupLayout.PREFERRED_SIZE, 278, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtBloodPressureView, javax.swing.GroupLayout.PREFERRED_SIZE, 278, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtTemperatureView, javax.swing.GroupLayout.PREFERRED_SIZE, 278, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(297, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jLabel1)
                .addGap(30, 30, 30)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(52, 52, 52)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnViewDetails)
                    .addComponent(btnDelete)
                    .addComponent(btnUpdate))
                .addGap(53, 53, 53)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTemperature)
                    .addComponent(txtTemperatureView, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(44, 44, 44)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblBloodPressure)
                    .addComponent(txtBloodPressureView, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(44, 44, 44)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblPulse)
                    .addComponent(txtPulseView, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(44, 44, 44)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblDate)
                    .addComponent(txtDateView, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(110, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnViewDetailsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewDetailsActionPerformed
        // TODO add your handling code here:
        int selectedrow= tblVitalSigns.getSelectedRow();
        
        if(selectedrow>=0){
            VitalSign vs = (VitalSign)tblVitalSigns.getValueAt(selectedrow,0);
            txtBloodPressureView.setText(String.valueOf(vs.getBloodPressure()));
            txtTemperatureView.setText(String.valueOf(vs.getTemperature()));
            txtPulseView.setText(String.valueOf(vs.getPulse()));
            txtDateView.setText(String.valueOf(vs.getDate()));
                       
        }
        else 
            JOptionPane.showMessageDialog(null,"Please Select A Row");
    }//GEN-LAST:event_btnViewDetailsActionPerformed

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
         // TODO add your handling code here:
        /* int selectedrow= tblVitalSigns.getSelectedRow();
        
        if(selectedrow>=0){
            VitalSign vs = (VitalSign)tblVitalSigns.getValueAt(selectedrow,0);
            vsh.deleteVitals(vs);
            JOptionPane.showMessageDialog(null,"Vital Sign Deleted Successfully");
            populateTable();
        
        }
        else 
            JOptionPane.showMessageDialog(null,"Please Select A Row");
       
        
     */   
    }//GEN-LAST:event_btnDeleteActionPerformed

    private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateActionPerformed
        // TODO add your handling code here:
        int selectedrow= tblVitalSigns.getSelectedRow();
        
        if(selectedrow>=0){
            VitalSign vsu = (VitalSign)tblVitalSigns.getValueAt(selectedrow,0);
            
            
        double temperature= Double.parseDouble(txtTemperatureView.getText());
        double bp= Double.parseDouble(txtBloodPressureView.getText());
        int pulse= Integer.parseInt(txtPulseView.getText());
        String date= txtDateView.getText();
        
        
        vsu.setBloodPressure(bp);
        vsu.setTemperature(temperature);
        vsu.setDate(date);
        vsu.setPulse(pulse);
        JOptionPane.showMessageDialog(null, "Vital Signs Updated Successfully");
        
        txtBloodPressureView.setText("");
        txtDateView.setText("");
        txtPulseView.setText("");
        txtTemperatureView.setText("");
            
            
            
            populateTable();
        
        }
        else 
            JOptionPane.showMessageDialog(null,"Please Select A Row");
        
        
        
    }//GEN-LAST:event_btnUpdateActionPerformed

    private void txtDateViewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDateViewActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDateViewActionPerformed

    private void txtTemperatureViewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTemperatureViewActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTemperatureViewActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnUpdate;
    private javax.swing.JButton btnViewDetails;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblBloodPressure;
    private javax.swing.JLabel lblDate;
    private javax.swing.JLabel lblPulse;
    private javax.swing.JLabel lblTemperature;
    private javax.swing.JTable tblVitalSigns;
    private javax.swing.JTextField txtBloodPressureView;
    private javax.swing.JTextField txtDateView;
    private javax.swing.JTextField txtPulseView;
    private javax.swing.JTextField txtTemperatureView;
    // End of variables declaration//GEN-END:variables
}
