/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interface;

import Business.VitalSignHistory;
import Business.VitalSign;
import javax.swing.JOptionPane;
 


/**
 *
 * @author Shail
 */
public class CreateVitalJPanel extends javax.swing.JPanel {

    /**
     * Creates new form CreateVitalJPanel
     */
    
    private VitalSignHistory vsh;

    public CreateVitalJPanel(VitalSignHistory vsh) {
        initComponents();
        this.vsh= vsh;   
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        labelAge = new javax.swing.JLabel();
        labelRespiratoryRate = new javax.swing.JLabel();
        labelWeightKG = new javax.swing.JLabel();
        labelBloodPressure = new javax.swing.JLabel();
        txtAge = new javax.swing.JTextField();
        txtRespRate = new javax.swing.JTextField();
        txtHeartRate = new javax.swing.JTextField();
        txtBP = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        btnSave = new javax.swing.JButton();
        labelHeartRate = new javax.swing.JLabel();
        txtWeightKG = new javax.swing.JTextField();
        labelWeightPounds = new javax.swing.JLabel();
        txtWeightPounds = new javax.swing.JTextField();

        setPreferredSize(new java.awt.Dimension(600, 600));
        setRequestFocusEnabled(false);

        labelAge.setText("age group");

        labelRespiratoryRate.setText("Respiratory Rate");

        labelWeightKG.setText("Weight in kilos");

        labelBloodPressure.setText("Blood Pressure");

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel1.setText("Create Vital Signs");

        btnSave.setText("Save");
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });

        labelHeartRate.setText("Heart Rate");

        txtWeightKG.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtWeightKGActionPerformed(evt);
            }
        });

        labelWeightPounds.setText("Weight in Pounds");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(75, 75, 75)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(labelRespiratoryRate)
                            .addComponent(labelWeightKG)
                            .addComponent(labelBloodPressure)
                            .addComponent(labelAge, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(labelWeightPounds)
                            .addComponent(labelHeartRate))
                        .addGap(106, 106, 106)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtBP, javax.swing.GroupLayout.PREFERRED_SIZE, 278, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtHeartRate, javax.swing.GroupLayout.PREFERRED_SIZE, 278, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtRespRate, javax.swing.GroupLayout.PREFERRED_SIZE, 278, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtAge, javax.swing.GroupLayout.PREFERRED_SIZE, 278, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtWeightKG, javax.swing.GroupLayout.PREFERRED_SIZE, 278, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtWeightPounds, javax.swing.GroupLayout.PREFERRED_SIZE, 278, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(202, 202, 202)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 237, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(230, 230, 230)
                        .addComponent(btnSave)))
                .addContainerGap(42, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(56, 56, 56)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelAge)
                    .addComponent(txtAge, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(44, 44, 44)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelRespiratoryRate)
                    .addComponent(txtRespRate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(44, 44, 44)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtHeartRate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelHeartRate))
                .addGap(44, 44, 44)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelBloodPressure)
                    .addComponent(txtBP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(labelWeightKG)
                    .addComponent(txtWeightKG, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(42, 42, 42)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(labelWeightPounds)
                    .addComponent(txtWeightPounds, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(btnSave)
                .addContainerGap(93, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
     
        double ageGroup= Double.parseDouble(txtAge.getText());
        double respiratoryRate= Double.parseDouble(txtRespRate.getText());
        double heartRate= Double.parseDouble(txtHeartRate.getText());
        double bloodPressure= Double.parseDouble(txtBP.getText());
        double weightKgs= Double.parseDouble(txtWeightKG.getText());
        double weightPounds= Double.parseDouble(txtWeightPounds.getText());
        
        
        VitalSign v= vsh.addVitals();
        boolean isNormal = vsh.findNormality(v);
        v.setIsNormal(isNormal);
        v.setAgeGroup(ageGroup);
        v.setRespiratoryRate(respiratoryRate);
        v.setHeartRate(heartRate);
        v.setBloodPressure(bloodPressure);
        v.setWeightKgs(weightKgs);
        v.setWeightPounds(weightPounds);
        JOptionPane.showMessageDialog(null, "Vital Signs Added Successfully");
        
        txtAge.setText("");
        txtRespRate.setText("");
        txtBP.setText("");
        txtHeartRate.setText("");
        txtWeightKG.setText("");
        txtWeightPounds.setText("");
        

// TODO add your handling code here:
    }//GEN-LAST:event_btnSaveActionPerformed

    private void txtWeightKGActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtWeightKGActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtWeightKGActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSave;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel labelAge;
    private javax.swing.JLabel labelBloodPressure;
    private javax.swing.JLabel labelHeartRate;
    private javax.swing.JLabel labelRespiratoryRate;
    private javax.swing.JLabel labelWeightKG;
    private javax.swing.JLabel labelWeightPounds;
    private javax.swing.JTextField txtAge;
    private javax.swing.JTextField txtBP;
    private javax.swing.JTextField txtHeartRate;
    private javax.swing.JTextField txtRespRate;
    private javax.swing.JTextField txtWeightKG;
    private javax.swing.JTextField txtWeightPounds;
    // End of variables declaration//GEN-END:variables
}
