/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interface;
import Business.VitalSignHistory;
import Business.VitalSign;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Shail
 */
public class ViewVitalsJPanel extends javax.swing.JPanel {

    
    /**
     * Creates new form viewVitalsJPanel
     */
    
    private VitalSignHistory vsh;
    public ViewVitalsJPanel(VitalSignHistory vsh) {
          initComponents();
          this.vsh= vsh;
           populateTable();
           
    }
    
    public void populateTable(){
    
    DefaultTableModel dtm= (DefaultTableModel)tblVitalSigns.getModel();
    dtm.setRowCount(0);
    
    for(VitalSign vs : vsh.getVitalSignHistory()){
    
    Object row[]= new Object[1];
    
    row[0]= vs;
    dtm.addRow(row);
    
    }
    
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblVitalSigns = new javax.swing.JTable();
        btnViewDetails = new javax.swing.JButton();
        btnDelete = new javax.swing.JButton();
        lblPulse = new javax.swing.JLabel();
        txtAgeGroupView = new javax.swing.JTextField();
        lblDate = new javax.swing.JLabel();
        txtRespRateView = new javax.swing.JTextField();
        txtHeartRateView = new javax.swing.JTextField();
        txtBPView = new javax.swing.JTextField();
        lblTemperature = new javax.swing.JLabel();
        lblBloodPressure = new javax.swing.JLabel();
        btnUpdate = new javax.swing.JButton();
        lblDate1 = new javax.swing.JLabel();
        txtWeightKGView = new javax.swing.JTextField();
        lblDate2 = new javax.swing.JLabel();
        txtWeightPoundsView = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtIsNormalView = new javax.swing.JTextField();

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel1.setText("View Vital Signs");

        tblVitalSigns.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ageGroup"
            }
        ));
        jScrollPane1.setViewportView(tblVitalSigns);

        btnViewDetails.setText("View Vital Signs");
        btnViewDetails.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViewDetailsActionPerformed(evt);
            }
        });

        btnDelete.setText("Delete");
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });

        lblPulse.setText("heart rate");

        txtAgeGroupView.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtAgeGroupViewActionPerformed(evt);
            }
        });

        lblDate.setText("blood pressure");

        txtBPView.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtBPViewActionPerformed(evt);
            }
        });

        lblTemperature.setText("age group");

        lblBloodPressure.setText("respiratory rate");

        btnUpdate.setText("Update");
        btnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateActionPerformed(evt);
            }
        });

        lblDate1.setText("weight in kgs");

        txtWeightKGView.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtWeightKGViewActionPerformed(evt);
            }
        });

        lblDate2.setText("weight in pounds");

        txtWeightPoundsView.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtWeightPoundsViewActionPerformed(evt);
            }
        });

        jLabel2.setText("is the patient normal?");

        txtIsNormalView.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtIsNormalViewActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(227, 227, 227)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(76, 76, 76)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblTemperature)
                                    .addComponent(lblBloodPressure)
                                    .addComponent(lblPulse)
                                    .addComponent(lblDate))
                                .addGap(106, 106, 106)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtBPView, javax.swing.GroupLayout.PREFERRED_SIZE, 278, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtHeartRateView, javax.swing.GroupLayout.PREFERRED_SIZE, 278, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtRespRateView, javax.swing.GroupLayout.PREFERRED_SIZE, 278, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(txtAgeGroupView, javax.swing.GroupLayout.PREFERRED_SIZE, 278, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(98, 98, 98)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(txtIsNormalView, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel2)))))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblDate1)
                                    .addComponent(lblDate2))
                                .addGap(98, 98, 98)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtWeightPoundsView, javax.swing.GroupLayout.PREFERRED_SIZE, 286, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtWeightKGView, javax.swing.GroupLayout.PREFERRED_SIZE, 286, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(layout.createSequentialGroup()
                            .addContainerGap()
                            .addComponent(btnViewDetails)
                            .addGap(31, 31, 31)
                            .addComponent(btnUpdate)
                            .addGap(26, 26, 26)
                            .addComponent(btnDelete))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                            .addGap(76, 76, 76)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(65, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jLabel1)
                .addGap(30, 30, 30)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(52, 52, 52)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnViewDetails)
                    .addComponent(btnDelete)
                    .addComponent(btnUpdate))
                .addGap(53, 53, 53)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTemperature)
                    .addComponent(txtAgeGroupView, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(18, 18, 18)
                .addComponent(txtIsNormalView, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(4, 4, 4)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblBloodPressure)
                    .addComponent(txtRespRateView, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(44, 44, 44)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblPulse)
                    .addComponent(txtHeartRateView, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(44, 44, 44)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblDate)
                    .addComponent(txtBPView, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblDate1)
                    .addComponent(txtWeightKGView, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtWeightPoundsView, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblDate2))
                .addContainerGap(31, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnViewDetailsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewDetailsActionPerformed
        // TODO add your handling code here:
        int selectedrow= tblVitalSigns.getSelectedRow();
        
        if(selectedrow>=0){
            VitalSign vs = (VitalSign)tblVitalSigns.getValueAt(selectedrow,0);
            txtRespRateView.setText(String.valueOf(vs.getRespiratoryRate()));
            txtAgeGroupView.setText(String.valueOf(vs.getAgeGroup()));
            txtHeartRateView.setText(String.valueOf(vs.getHeartRate()));
            txtBPView.setText(String.valueOf(vs.getBloodPressure()));
            txtWeightKGView.setText(String.valueOf(vs.getWeightKgs()));
            txtWeightPoundsView.setText(String.valueOf(vs.getWeightPounds()));
            txtIsNormalView.setText(String.valueOf(vs.isIsNormal()));
        }
        else 
            JOptionPane.showMessageDialog(null,"Please Select A Row");
    }//GEN-LAST:event_btnViewDetailsActionPerformed

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
         // TODO add your handling code here:
         int selectedrow= tblVitalSigns.getSelectedRow();
        
        if(selectedrow>=0){
            VitalSign vs = (VitalSign)tblVitalSigns.getValueAt(selectedrow,0);
            vsh.deleteVitals(vs);
            JOptionPane.showMessageDialog(null,"Vital Sign Deleted Successfully");
            populateTable();
        
        }
        else 
            JOptionPane.showMessageDialog(null,"Please Select A Row");
       
        
        
    }//GEN-LAST:event_btnDeleteActionPerformed

    private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateActionPerformed
        // TODO add your handling code here:
        int selectedrow= tblVitalSigns.getSelectedRow();
        
        if(selectedrow>=0){
            VitalSign vsu = (VitalSign)tblVitalSigns.getValueAt(selectedrow,0);
            
            
        double ageGroup= Double.parseDouble(txtAgeGroupView.getText());
        double respiratoryRate= Double.parseDouble(txtRespRateView.getText());
        double heartRate= Double.parseDouble(txtHeartRateView.getText());
        double bloodPressure= Double.parseDouble(txtBPView.getText());
        double weightKgs= Double.parseDouble(txtWeightKGView.getText());
        double weightPounds= Double.parseDouble(txtWeightPoundsView.getText());
        
        
        
        
        vsu.setBloodPressure(bloodPressure);
        vsu.setAgeGroup(ageGroup);
        vsu.setRespiratoryRate(respiratoryRate);
        vsu.setHeartRate(heartRate);
        vsu.setWeightKgs(weightKgs);
        vsu.setWeightPounds(weightPounds);
        JOptionPane.showMessageDialog(null, "Vital Signs Updated Successfully");
        
        txtRespRateView.setText("");
        txtBPView.setText("");
        txtHeartRateView.setText("");
        txtAgeGroupView.setText("");
        txtWeightKGView.setText("");
        txtWeightPoundsView.setText("");
            
            
            
            populateTable();
        
        }
        else 
            JOptionPane.showMessageDialog(null,"Please Select A Row");
        
        
        
    }//GEN-LAST:event_btnUpdateActionPerformed

    private void txtBPViewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtBPViewActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtBPViewActionPerformed

    private void txtAgeGroupViewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtAgeGroupViewActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtAgeGroupViewActionPerformed

    private void txtWeightKGViewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtWeightKGViewActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtWeightKGViewActionPerformed

    private void txtWeightPoundsViewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtWeightPoundsViewActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtWeightPoundsViewActionPerformed

    private void txtIsNormalViewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtIsNormalViewActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtIsNormalViewActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnUpdate;
    private javax.swing.JButton btnViewDetails;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblBloodPressure;
    private javax.swing.JLabel lblDate;
    private javax.swing.JLabel lblDate1;
    private javax.swing.JLabel lblDate2;
    private javax.swing.JLabel lblPulse;
    private javax.swing.JLabel lblTemperature;
    private javax.swing.JTable tblVitalSigns;
    private javax.swing.JTextField txtAgeGroupView;
    private javax.swing.JTextField txtBPView;
    private javax.swing.JTextField txtHeartRateView;
    private javax.swing.JTextField txtIsNormalView;
    private javax.swing.JTextField txtRespRateView;
    private javax.swing.JTextField txtWeightKGView;
    private javax.swing.JTextField txtWeightPoundsView;
    // End of variables declaration//GEN-END:variables
}
